### ISSUE TITLE
[Images] Two Elements Gallery

### ISSUE THREAD

**Issue by Lory1990** [Lory1990/react-cool-components#3]
Creare il componente TwoElements tipo Gallery

Crearlo in gallery\TwoElements

![1626774419470](https://user-images.githubusercontent.com/7715601/134461390-101af885-5c7a-47a7-9f60-5d9f580fc4ad.gif)

**Comment by Lory1990** [comment]
Ciao Marco, per questo task puoi iniziare a creare un componente react dove passerai come props due immagini :) e poi lo vediamo insieme

Ti lascio le istruzioni per lavorare bene

1. Stacca un branch con _ -> mperetto_TwoElementsGallery
2. Crea la cartella gallery
3. Crea un cartella in gallery chiamata TwoElementsGallery
4. In TwoElementsGallery crea i files TwoElementsGallery.tsx, TwoElementsGallery.module.scss, TwoElementsGallery.stories.tsx, index.ts

Poi vediamo insieme come visualizzare il componente, si fa tramite "TwoElementsGallery.stories.tsx"

**Comment by mperetto** [comment]
Ciao ho creato il branch e aggiunto i file.

Poi ho creato il componente React su codepen prima di aggiungerlo a storybook.

Questo è link con il codice: [Creative img clip-path effect React-component](https://codepen.io/mperetto/pen/MWoRGzB).

**Comment by Lory1990** [comment]
Ciao Marco,
ottimo codice, ho fatto qualche micro modifica  sul CSS
- Tra le props ho aggiunto gli attributi ALT
- Per visualizzare il CSS devi scrivere style[classeCSS] altrimenti non lo prende, questi sono i [CSS modules](https://css-tricks.com/css-modules-part-1-need/)
- Nelle props ho aggiunto l'attributo "classes" che serve a specificare le classi per ciascun elemento (in questo caso le immagini)
- Ho aggiunto tra le prps il className del componente

E nella storia
- Ho aggiunto tre storie che devi completare: solo img SX, solo img DX, no imgs -> Devi gestire questi casi perché gli sviluppatori sono distratti
- Ho messo il componente sotto Gallery

anyway OTTIMO LAVORO :)

**Comment by mperetto** [comment]
Ciao ho implementato le 3 nuove storie, in pratica per le immagini singole ho rimosso il clip-path e le ho visualozzate a schermo intero.
Invece per le immagini mancanti al loro posto ho visualizzato un linear gradient come background del container.

**Comment by Lory1990** [comment]
@mperetto ci siamo, proprio ora sto facendo il Deploy della tua carta :) Il task è chiuso 

Ho modificato un attimo il tuo codice per inserire la logica all'interno del tuo componente  e non nella logica
